{{- if .Values.daggen.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.daggen.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.daggen.appLabel }}
spec:
  replicas: {{ .Values.daggen.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.daggen.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.daggen.appLabel }}
    spec:
      containers:
        - name: {{ .Values.daggen.name }}
          image: {{ .Values.daggen.image.repository }}:{{ .Values.daggen.image.tag }}
          imagePullPolicy: {{ .Values.daggen.image.pullPolicy }}
          env:
            - name: REGISTRY_URL
              value: "{{ .Values.daggen.env.REGISTRY_URL }}"
            - name: REGISTRY_PORT
              value: "{{ .Values.daggen.env.REGISTRY_PORT }}"
            - name: AIRFLOW_URL
              value: "{{ .Values.daggen.env.AIRFLOW_URL }}"
            - name: AIRFLOW_PUBLIC_URL
              value: "http://{{ .Values.global.deviceIP }}:{{ (index .Values.airflow.webserver.service.ports 0).port }}"
            - name: PUBLIC_IP
              value: "{{ .Values.global.deviceIP }}"
          securityContext:
            runAsUser: {{ .Values.daggen.runAsUser }}
{{- end }}
