{{- if .Values.daggen.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.daggen.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.daggen.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.daggen.service.port }}
      targetPort: {{ .Values.daggen.service.targetPort }}
  type: {{ .Values.daggen.service.type }}
{{- end }}
