apiVersion: v1
kind: Secret
metadata:
  name: my-airflow-connections
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AIRFLOW_CONN_AWS: {{ printf "aws://%s:%s@/?endpoint_url=http%%3A%%2F%%2Fai-toolkit-minio%%3A9000" .Values.minio.auth.rootUser .Values.minio.auth.rootPassword | b64enc }}
